name: "Build Package Listing"

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gomorroth/vpm-build-repository@v1.1
        
      - run : |
          ls -l
          cat vpm.json
