name: "Github Rest API"

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: "1"
        run: |
          curl https://api.github.com/rate_limit

            
      - name: "2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl https://api.github.com/rate_limit
